### ISSUE TITLE
Add support to set PWM frequencies above 500kHz

### ISSUE THREAD

**Issue by kalleadolfsson** [khoih-prog/Portenta_H7_PWM#2]
I'm quite new to PWM and interrupts and I am currently trying to setup communication with a linear image sensor (TCD1304AP) that requires a PWM frequency of around 2MHz for the master clock. The highest frequency I have been able to achieve with my Portenta H7 Lite is 500kHz (verified with scope).

I realize a higher clock frequency could be achieved with an external clock but considering the high clock frequency of the STM32H7 It would have been great if this high speed could be leveraged directly from the MCU.

I have tried to set the prescaler for the timer being used but I still can't achieve 500kHz frequencies.

Thank you for an otherwise awsome lib.
Best,
Kalle

**Comment by khoih-prog** [comment]
Hi @kalleadolfsson 

Thanks for your interest in and your nice words about the library.

I'm sorry I don't have time now to look at the issue. As the library is just a **simple wrapper** around the **mbed_portenta** core, it's better that you post the issue for help on the [**ArduinoCore-mbed** core](https://github.com/arduino/ArduinoCore-mbed), certainly it's necessary to use the core's PWM code to write [**Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example) to prove that this is some necessary enhancement for the core.

I also suggest that you use the much cheaper **RP2040** and my [**RP2040_PWM** library](https://github.com/khoih-prog/RP2040_PWM). Check [**Why do we need this RP2040_PWM library**](https://github.com/khoih-prog/RP2040_PWM#why-do-we-need-this-rp2040_pwm-library)

> These purely hardware-based PWM channels can generate from very low (lowest is 7.5Hz) to very high PWM frequencies (in the MHz range, up to 62.5MHz)

I'm closing the issue now as this is not the bug of the library, but some limitation of the core / chip and I won't spend time on this matter. 

Any update from you will be much appreciated.

Good Luck,

<img width="1232" alt="RPi_Pico_Pinout" src="https://user-images.githubusercontent.com/57012152/157948880-dcba287f-299b-4532-b114-4960b9dce51f.png">

**Comment by kalleadolfsson** [comment]
Hi, 
Ok thanks for your suggestions!
Keep up the good work
Cheers,
Kalle
